version: '2'
services:
    jhipster_ng_lightning-app:
        image: jhipster_ng_lightning
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster_ng_lightning-postgresql:5432/jhipster_ng_lightning
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster_ng_lightning-postgresql:
        extends:
            file: postgresql.yml
            service: jhipster_ng_lightning-postgresql
